#!/bin/bash

browserify ./dist/index.js > ./dist/bundle.js
node-minify --compressor uglify-es --input './dist/bundle.js' --output './dist/bundle.min.js'
yarn javascript-obfuscator './dist/bundle.min.js' --output './public/assets/js/bundle.min.js' --string-array false
